"""add sync_change_log table

Revision ID: 4bc3a906e93f
Revises: e0c108c5f4dd
Create Date: 2026-09-02 20:41:32.537188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc3a906e93f'
down_revision: Union[str, Sequence[str], None] = 'e0c108c5f4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('COURSE', 'ASSIGNMENT', 'CALENDAR_EVENT', name='syncentitytype', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False, comment='Local DB id of the affected row.'),
    sa.Column('canvas_id', sa.String(), nullable=True),
    sa.Column('change_type', sa.Enum('CREATED', 'UPDATED', 'DELETED', name='syncchangetype', native_enum=False), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True, comment='Null when change_type is created/deleted (whole-entity change).'),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_change_log')
    # ### end Alembic commands ###
