"""add description, score, grade to assignments

Revision ID: 676a0c2aac88
Revises: e744ec1aca5d
Create Date: 2026-09-03 17:04:28.034600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676a0c2aac88'
down_revision: Union[str, Sequence[str], None] = 'e744ec1aca5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('description', sa.Text(), nullable=True, comment='Assignment instructions, from the Canvas REST API or browser scraping.'))
    op.add_column('assignments', sa.Column('score', sa.Float(), nullable=True, comment='Points earned, where Canvas exposes a numeric score.'))
    op.add_column('assignments', sa.Column('grade', sa.String(), nullable=True, comment='Displayed grade as Canvas shows it (letter, percentage, complete/incomplete, etc.) -- not always numeric, so kept separate from `score`.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'grade')
    op.drop_column('assignments', 'score')
    op.drop_column('assignments', 'description')
    # ### end Alembic commands ###
