"""initial v1 schema

Revision ID: e0c108c5f4dd
Revises: 
Create Date: 2026-09-02 20:34:14.176521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c108c5f4dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canvas_course_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('credit_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canvas_course_id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CANVAS_API', 'CANVAS_CALENDAR_AUTO', 'SYLLABUS', 'PROFESSOR_ANNOUNCEMENT', 'LECTURE_RECORDING', 'USER_STATED', 'CLAUDE_INFERRED', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('base_authority_weight', sa.Integer(), nullable=False, comment='Default weight 1-100; higher wins in the absence of other signals.'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('assessment_type', sa.Enum('EXAM', 'QUIZ', 'FINAL', 'OTHER', name='assessmenttype', native_enum=False), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weight_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('canvas_assignment_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('points_possible', sa.Float(), nullable=True),
    sa.Column('canvas_status', sa.String(), nullable=True, comment='Raw Canvas submission status signal, NOT the local task state.'),
    sa.Column('canvas_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canvas_assignment_id')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('canvas_event_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('CLASS', 'EXAM', 'WORK', 'OTHER', name='calendareventtype', native_enum=False), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canvas_event_id')
    )
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('parent_concept_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['parent_concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('SYLLABUS', 'LECTURE', 'NOTES', 'STUDY_GUIDE', 'OTHER', name='documentsourcetype', native_enum=False), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=True, comment='1-5; null means even weighting against other linked concepts.'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'concept_id')
    )
    op.create_table('assessment_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'document_id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_or_slide', sa.String(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True, comment="Reserved for v1's embedding pipeline; unused by the foundation."),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index')
    )
    op.create_table('episodic_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False, comment='Free-text key, e.g. "CHEM1010 final exam date".'),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('explicitness', sa.Enum('EXPLICIT_STATEMENT', 'INFERRED', 'DEFAULT_TEMPLATE', name='factexplicitness', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='factconfidence', native_enum=False), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_by_fact_id', sa.Integer(), nullable=True),
    sa.Column('conflict_status', sa.Enum('NONE', 'UNRESOLVED', 'RESOLVED', name='factconflictstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_fact_id'], ['facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mastery_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('QUIZ_ANSWER', 'STUDY_SESSION', 'SELF_REPORT', 'MISTAKE_FLAGGED', name='masteryeventtype', native_enum=False), nullable=False),
    sa.Column('outcome', sa.Enum('CORRECT', 'INCORRECT', 'PARTIAL', 'SELF_RATED', name='masteryoutcome', native_enum=False), nullable=False),
    sa.Column('outcome_score', sa.Float(), nullable=False, comment='Normalized 0.0-1.0 outcome, used by the derived-score calculation.'),
    sa.Column('self_rating', sa.Integer(), nullable=True, comment='1-5, only set when event_type=self_report.'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_description', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_session_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_session_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_session_id', 'concept_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('related_assignment_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('task_type', sa.Enum('READING', 'STUDYING', 'WORKSHEET', 'PREP', 'REVIEW', 'OTHER', name='tasktype', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'DONE', 'SKIPPED', 'BLOCKED', name='taskstate', native_enum=False), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['related_assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'NOTABLE', 'AMBIENT', name='notificationseverity', native_enum=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('related_course_id', sa.Integer(), nullable=True),
    sa.Column('related_task_id', sa.Integer(), nullable=True),
    sa.Column('related_assessment_id', sa.Integer(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['related_course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['related_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('tasks')
    op.drop_table('study_session_concepts')
    op.drop_table('mastery_events')
    op.drop_table('facts')
    op.drop_table('episodic_notes')
    op.drop_table('document_chunks')
    op.drop_table('assessment_documents')
    op.drop_table('assessment_concepts')
    op.drop_table('study_sessions')
    op.drop_table('documents')
    op.drop_table('concepts')
    op.drop_table('calendar_events')
    op.drop_table('assignments')
    op.drop_table('assessments')
    op.drop_table('sources')
    op.drop_table('courses')
    # ### end Alembic commands ###
